# .kodiak.toml
[merge]
delete_branch_on_merge = true
automerge_label = ["ğŸ£ - snyc tokenlist", "automerge"]


[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["dependabot", "github-actions"]

[update]
ignored_usernames = ["dependabot", "github-actions"]
